# configuration of 3DCNN

#use sampler to generate batches with similar distributions.
use_sampler: False
# number of folds in training set.
folds: 5
# model name
model_name: CNN
# batch size
batch_size: 1024
# number of epochs need to be run
epochs: 9
# number of input channels, C, N, O, S
num_channels: 4
# number of output predicted classes, 20 amino acids
num_classes: 20
# Use transformation to the data set or not (Gaussian Filter):
use_transform: False
# model checkpoint path
model_ckpt_path: model_checkpoints
# number of workers
num_workers: 8
# optimizer
optimizer: SGD
# base learning rate
lr: 5e-3
# learning rate maximum
lr_max: 5e-3
# learning rate min
lr_min: 1e-5
# learning rate cosine period
lr_period: 1000
# warm up step
warm_up_step: 500
# validation step: after x steps the validation process end
validation_step: 500
# drop out rate
drop_out: 0