# This is the configuration file of voxel box generation script.
# All configuration is for generating one voxel box at a time.

# PDB file path

# Add hydrogen to the pdb file or not
addH: False
# Add partial charges to the file or not (atom.occupancy = partial charges)
add_partial_charges: False
# Add sasa to the file or not (atom.bfactor = atom radii)
add_sasa: False
# PDB pure ID
pdb_name: "3gbn"
# PDB file path
pdb_path: "3gbn.pdb"
# PDB id
pdb_id:
# hdf5 directory path
hdf5_file_dir: